### ISSUE TITLE
feature request: url params for highlighting a line or range

### ISSUE THREAD

**Issue by kumavis** [g-harel/npmfs#5]
thank you for npmfs! :purple_heart: 
im working on some static analysis of popular npm packages.
it would be great if I could generate links pointing to specific lines and/or a range, as in github

**Comment by kumavis** [comment]
oh wow you can already do this :clap: 
is there a handy way to do it in the ui? ( like clicking the line numbers )

**Comment by g-harel** [comment]
Glad to hear you're enjoying it!

When hovering over a line, the three dots at the far right are a self-link. Seems like this is might not be super intuitive, do you have any suggestions for a better UI?

https://npmfs.com/package/express/4.17.1/Readme.md#L16
https://npmfs.com/compare/express/4.17.0/4.17.1/#D0L3

**Comment by g-harel** [comment]
Also regarding ranges, they're not supported yet but I can look into it.

**Comment by kumavis** [comment]
ah yes, the three dots definitely works, didn't notice that before. i think clicking the line numbers (as on github) would be more intuitive.

ranges would be useful

my tool produces line + col start and end points which are especially helpful when working with minified code
in this example, you can't even tell what what the relevant code is https://npmfs.com/package/truffle-hdwallet-provider/1.0.17/dist/index.js#L15
so obviously being able to specify a range with column accuracy would be helpful to me, but not sure how complex implementation is

**Comment by g-harel** [comment]
I like the line number suggestion, change should be live when the workflow completes! I couldn't entirely remove the three dot element because, on diff pages, line numbers link to the original source line, not to themselves.

About the ranges, I think it would be good value to be able to link to a range and I have a pretty good idea of how I can make it work. The hardest part about this would probably be UI to generate this link, but I don't think you would need that for your use-case.

I'm thinking something like `#L91:12-L94:34` where both the column number and second line/column combo are optional. Let me know what you think!

**Comment by g-harel** [comment]
Implemented line range links! https://npmfs.com/package/bluebird/3.5.5/js/release/promise_array.js#L124-L135

**Comment by g-harel** [comment]
This should now be working, you can use this format to link and highlight specific ranges:
https://npmfs.com/compare/bluebird/3.5.4/3.5.5/#D0L24:12-L24:36

**Comment by kumavis** [comment]
thanks @g-harel ! great stuff

this feature is https://npmfs.com/package/bluebird/3.5.5/package.json#L3:63-L3:82

**Comment by kumavis** [comment]
@g-harel heres the column-level range feature really shining https://npmfs.com/package/netlify-cms/2.10.51/dist/netlify-cms.js#L155:452867-L155:452874

**Comment by g-harel** [comment]
Glad to hear that! Page load is really slow though, I'll have to check that out
